  name: Smoke Tests Run

  on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

  jobs:
    build:
    
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'
          cache: maven
          # cache-dependency-path: 'sub-project/pom.xml' # optional

      - name: Setup Chrome
      - uses: browser-actions/setup-chrome@latest
      - run:  chrome --version

      - name: Setup Firefox
      - uses: browser-actions/setup-firefox@latest
      - run:  firefox --version

      - name: Setup Edge
      - uses: browser-actions/setup-edge@latest
      - run:  (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion



      - name: Build with Maven
        run: mvn -B clean test
