name: Java CI with Maven and Allure

on:
    workflow_dispatch:
      inputs:
        chosen-os:
          description: 'Select OS'
          required: true
          default: 'ubuntu-latest'
          type: choice
          options:
          - ubuntu-latest

jobs:
  build:
    runs-on: ["${{ inputs.chosen-os }}"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean test

      - name: Download Allure Command Line
        run: wget -O allure-2.14.0.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.tgz && tar -zxvf allure-2.24.0.tgz

      - name: Generate Allure Report
        run: ./allure-2.24.0/bin/allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
