  name: Smoke Tests Run

  on:
    workflow_dispatch:
      inputs:
        chosen-os:
          description: 'Select OS'
          required: true
          default: 'Windows'
          type: choice
          options:
          - Ubuntu
          - Windows
          - MacOS

  jobs:
    build:

      runs-on: [self-hosted, "${{ inputs.chosen-os }}"]

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'
          # cache: maven
          # cache-dependency-path: 'sub-project/pom.xml' # optional

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - run:  chrome --version

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
      - run:  firefox --version

      - name: Setup Edge
        if: "github.event.inputs.chosen-os == 'Windows'"
        uses: browser-actions/setup-edge@latest
      - run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
